### ISSUE TITLE
Value of two tail area

### ISSUE THREAD

**Issue by gdcumming** [gfmoore/esci-distributions#6]
Both tabs: When Two tails and Areas are both ON, can we have a report of the total of the two tail areas, as in ESCI? 
Maybe, as in ESCI, the ‘Two tails’ label, and the value, could both be displayed just above the R tail area value, and moving with the R tail cursor.

**Comment by gfmoore** [comment]
Done. Added a subtle background colour just so it looked different from the two tail probabilities. btw the sum is of the displayed probabilities.

**Comment by gdcumming** [comment]
0.1.12
label, position, value--all look good

**Comment by gdcumming** [comment]
0.1.12

After further playing:
In either tab, with Normal displayed, the vertical positions of all the area values are good. But when t curve is displayed, the value of the central area (between the two tails) shifts higher, so the values don't miss each other neatly when tails get close to the centre. Please shift that central area value down a bit, to where it is for Normal.

Reflecting on the black rectangles around the area values: I like the way the report of X values are reported  (near top of cursors) without a box around, just a white rectangle. (As in ESCI.) Could we try removing the boxes around all the area values?

Let's try it also without the pale cream shading for central area value, and pale green (?) for two-tail area.

In ESCI I was concerned that, when both normal and t curves are visible, it might be unclear which tail area value was being reported. Yes, the tail area is either red or blue, but even so... In ESCI I included a kludgy note in the plot saying 'Probabilities are areas under the red curve (t)'. I'm not asking for such a note!

But, how about we try having the tail area values themselves in blue numbers for Normal and red numbers for t? Central area could remain black in all cases--quite clear, now that this value moves to stay in that central area. The two-tail value could be blue or red, with its position and the 'two tail' label sufficient, I think, to make it clear what it is.

**Comment by gfmoore** [comment]
Middle value shifted down.
Pity, I liked the rectangles and colours, but I've done as you requested. The problem is that the white background rectangle looks odd especially as it moves into a shaded area.

I think this is done. I hope I don't have to keep tweaking this! It's such a pain this trial and error! It takes up more time than almost anything else :) The problem is that you know what's in your mind and I don't so I try and do what I think looks good, but it's hardly ever what you want! If you wanted you could "clone" the code and then I'll point you to where the code is and you can tweak to your heart's content and then let me have a copy of the code you've tweaked? Well it's a possibility to consider especially for the future applications?

**Comment by gdcumming** [comment]
0.1.18

Thank you, thank you. I think this looks terrific. I know I was being a pain to request the box and colour changes.

When I first saw the boxes I felt without boxes might have looked better (as in ESCI) but not sufficient a big deal to change. Then the X=value you made looked so good, and my concern to have more clearly a signal of normal/t for the tails in the t tab, prompted the requests.

Another aspect was that, in making the Fig for Ch 5, the value looked to overpower the shaded tail itself. With the no-box and slightly smaller font I think that's no longer a concern.

Did I mention that the sliders work wonderfully?
